/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BusBookingSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author HP
 */
public class AddBooking extends javax.swing.JFrame {

    /**
     * Creates new form AddBooking
     */
    public AddBooking() {
        initComponents();
        this.setResizable(false);
        
        try{
            // Travel Schedule Table
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/busbookingsystem","root","");
            String sql = "SELECT * FROM `travel-schedule-table`";
            PreparedStatement table = con.prepareStatement(sql);
            ResultSet result = table.executeQuery();
            while(result.next()){
                String travel_id = String.valueOf(result.getInt("travel-id"));
                String bus_id = String.valueOf(result.getInt("bus-id"));
                String starting_point = result.getString("starting-point");
                String destination = result.getString("destination");
                String depart_time = result.getString("depart-time");
                String depart_date = String.valueOf(result.getDate("depart-date"));
                String remaining_seats = String.valueOf(result.getInt("remaining-seats"));
                String ticket_price =  String.valueOf(result.getInt("ticket-price"));
                String Travel_Schedule[] = {travel_id,bus_id,starting_point,destination,depart_time,depart_date,remaining_seats,ticket_price};
                DefaultTableModel TableModel = (DefaultTableModel)Travel_Schedule_ListTable.getModel();
                TableModel.addRow(Travel_Schedule);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DepartDate = new com.toedter.calendar.JDateChooser();
        StartringPoint = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Distination = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Travel_ScheduleTable = new javax.swing.JTable();
        BttnSearch = new javax.swing.JButton();
        DepartTime = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Travel_Schedule_ListTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        BttnLogout = new javax.swing.JButton();
        BttnMyBooking = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        customer_name = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));

        jPanel1.setBackground(new java.awt.Color(255, 225, 184));

        jPanel2.setBackground(new java.awt.Color(255, 225, 184));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel2.setText("Startring point");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel3.setText("Depart Date");

        DepartDate.setBackground(new java.awt.Color(255, 225, 184));

        StartringPoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jerusalem", "Ramallah", "Acre", "Tulkarm", "Nablus", "Haifa", "Hebron", "Gaza", "Jaffa", "Jericho", "Bethlehem", "Nazareth", "Jenin", "Qalqilya", "Tubas" }));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel5.setText("Distination");

        Distination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jerusalem", "Ramallah", "Acre", "Tulkarm", "Nablus", "Haifa", "Hebron", "Gaza", "Jaffa", "Jericho", "Bethlehem", "Nazareth", "Jenin", "Qalqilya", "Tubas" }));
        Distination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistinationActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel4.setText("Depart time");

        Travel_ScheduleTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Travel_ScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Travel ID", "Bus ID", "Starting Point", "Destination", "Depart Time", "Depart Date", "Remaining Seats", "Ticket Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Travel_ScheduleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Travel_ScheduleTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(Travel_ScheduleTable);
        if (Travel_ScheduleTable.getColumnModel().getColumnCount() > 0) {
            Travel_ScheduleTable.getColumnModel().getColumn(0).setResizable(false);
            Travel_ScheduleTable.getColumnModel().getColumn(1).setResizable(false);
            Travel_ScheduleTable.getColumnModel().getColumn(2).setResizable(false);
            Travel_ScheduleTable.getColumnModel().getColumn(3).setResizable(false);
            Travel_ScheduleTable.getColumnModel().getColumn(4).setResizable(false);
            Travel_ScheduleTable.getColumnModel().getColumn(5).setResizable(false);
            Travel_ScheduleTable.getColumnModel().getColumn(6).setResizable(false);
            Travel_ScheduleTable.getColumnModel().getColumn(7).setResizable(false);
        }

        BttnSearch.setBackground(new java.awt.Color(193, 222, 252));
        BttnSearch.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        BttnSearch.setText("Search");
        BttnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(DepartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(StartringPoint, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Distination, 0, 107, Short.MAX_VALUE)
                            .addComponent(DepartTime)))
                    .addComponent(BttnSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartringPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(Distination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DepartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(DepartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(BttnSearch)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 225, 184));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Travel_Schedule_ListTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Travel_Schedule_ListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Travel ID", "Bus ID", "Starting Point", "Destination", "Depart Time", "Depart Date", "Remaining Seats", "Ticket Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(Travel_Schedule_ListTable);
        if (Travel_Schedule_ListTable.getColumnModel().getColumnCount() > 0) {
            Travel_Schedule_ListTable.getColumnModel().getColumn(0).setResizable(false);
            Travel_Schedule_ListTable.getColumnModel().getColumn(1).setResizable(false);
            Travel_Schedule_ListTable.getColumnModel().getColumn(2).setResizable(false);
            Travel_Schedule_ListTable.getColumnModel().getColumn(3).setResizable(false);
            Travel_Schedule_ListTable.getColumnModel().getColumn(4).setResizable(false);
            Travel_Schedule_ListTable.getColumnModel().getColumn(5).setResizable(false);
            Travel_Schedule_ListTable.getColumnModel().getColumn(6).setResizable(false);
            Travel_Schedule_ListTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 225, 184));

        BttnLogout.setBackground(new java.awt.Color(255, 184, 190));
        BttnLogout.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        BttnLogout.setText("Logout");
        BttnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnLogoutActionPerformed(evt);
            }
        });

        BttnMyBooking.setBackground(new java.awt.Color(193, 222, 252));
        BttnMyBooking.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        BttnMyBooking.setText("My Booking");
        BttnMyBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnMyBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BttnMyBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BttnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BttnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BttnMyBooking, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Welcome");

        customer_name.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        customer_name.setText("User name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customer_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel54.setBackground(new java.awt.Color(255, 184, 190));
        jPanel54.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel54.setForeground(new java.awt.Color(51, 102, 255));
        jPanel54.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Bus Ticket Booking System");

        javax.swing.GroupLayout jPanel54Layout = new javax.swing.GroupLayout(jPanel54);
        jPanel54.setLayout(jPanel54Layout);
        jPanel54Layout.setHorizontalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel54Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel54Layout.setVerticalGroup(
            jPanel54Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel54Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1337, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DistinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistinationActionPerformed

    private void BttnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnLogoutActionPerformed
        UserLogin user = new UserLogin();
        user.setVisible(true); // go to login page
        this.setVisible(false); // hide this page
    }//GEN-LAST:event_BttnLogoutActionPerformed

    private void BttnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnSearchActionPerformed
        try{
            String Starting = StartringPoint.getSelectedItem().toString();
            String destination = Distination.getSelectedItem().toString();        
            java.sql.Date sqlDate = new java.sql.Date((DepartDate.getDate()).getTime()); // convert from java date to sql date
            
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/busbookingsystem","root","");
                String sql = "SELECT * FROM `travel-schedule-table` WHERE `starting-point`=? AND `destination`=? AND `depart-date`=? AND `depart-time`=?";
                PreparedStatement stmt=con.prepareStatement(sql);
                stmt.setString(1, Starting);
                stmt.setString(2, destination);
                stmt.setDate(3, sqlDate);
                stmt.setString(4, DepartTime.getText());
                ResultSet resultTable = stmt.executeQuery();
                while(resultTable.next()){
                    String bus_id = String.valueOf(resultTable.getInt("bus-id"));
                    String starting_point = resultTable.getString("starting-point");
                    String ddestination = resultTable.getString("destination");
                    String depart_time = resultTable.getString("depart-time");
                    String depart_date = String.valueOf(resultTable.getDate("depart-date"));
                    String remaining_seats = String.valueOf(resultTable.getInt("remaining-seats"));
                    String ticket_price =  String.valueOf(resultTable.getInt("ticket-price"));
                    String Travel_Schedule[] = {bus_id,starting_point,ddestination,depart_time,depart_date,remaining_seats,ticket_price};
                    DefaultTableModel TableModel = (DefaultTableModel)Travel_ScheduleTable.getModel();
                    TableModel.addRow(Travel_Schedule);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Add date before search");
        }
        
    }//GEN-LAST:event_BttnSearchActionPerformed

    private void Travel_ScheduleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Travel_ScheduleTableMouseClicked
        ConfirmBooking form = new ConfirmBooking();
        int index = Travel_ScheduleTable.getSelectedRow();
        TableModel model = Travel_ScheduleTable.getModel();
        String bus_id = model.getValueAt(index,0).toString();
        String starting_point = model.getValueAt(index,1).toString();
        String destination = model.getValueAt(index,2).toString();
        String depart_time = model.getValueAt(index,3).toString();
        String depart_date = model.getValueAt(index,4).toString();
        String remaining_seats = model.getValueAt(index,5).toString();
        String ticket_price = model.getValueAt(index,6).toString();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/busbookingsystem","root","");
            String sql = "SELECT `customer-id`, `customer-name` FROM `customer-table` WHERE `customer-name`=?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, customer_name.getText());
            ResultSet result = stmt.executeQuery();
            if(result.next()){
                String CustomerID = result.getString("customer-id");
                String CustomerName = result.getString("customer-name");
                form.customer_name.setText(CustomerName);
                form.customer_id.setText(CustomerID);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        form.setVisible(true); // go to Confirm booking page
        this.setVisible(false); // hide this page
        form.bus_id.setText(bus_id);
        form.starting_point.setText(starting_point);
        form.destination.setText(destination);
        form.depart_time.setText(depart_time);
        form.depart_date.setText(depart_date);
        form.remaining_seats.setText(remaining_seats);
        form.ticket_price.setText(ticket_price);
        
    }//GEN-LAST:event_Travel_ScheduleTableMouseClicked

    private void BttnMyBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnMyBookingActionPerformed
        MyBooking my_booking_page = new MyBooking();
        AddBooking user = new AddBooking();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/busbookingsystem","root","");
            String sql = "SELECT * FROM `booking-table` WHERE `customer-name`=?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, customer_name.getText());
            ResultSet result = stmt.executeQuery();
            while(result.next()){
                String booking_id = String.valueOf(result.getInt("booking-id"));
                String bus_id = String.valueOf(result.getInt("bus-id"));
                String customer_id = String.valueOf(result.getInt("customer-id"));
                String customer_namee = result.getString("customer-name");
                String seat_number = String.valueOf(result.getInt("seat-number"));
                String paid = result.getString("paid");
                String MyBooking[] = {booking_id,bus_id,customer_id,customer_namee,seat_number,paid};
                DefaultTableModel TableModel = (DefaultTableModel)my_booking_page.MyBookingTable.getModel();
                TableModel.addRow(MyBooking);
            }
            my_booking_page.customer_name.setText(customer_name.getText());
            my_booking_page.setVisible(true); // go to by booking page
            this.setVisible(false); // hide this page
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BttnMyBookingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnLogout;
    private javax.swing.JButton BttnMyBooking;
    private javax.swing.JButton BttnSearch;
    private com.toedter.calendar.JDateChooser DepartDate;
    private javax.swing.JTextField DepartTime;
    private javax.swing.JComboBox<String> Distination;
    private javax.swing.JComboBox<String> StartringPoint;
    public javax.swing.JTable Travel_ScheduleTable;
    public javax.swing.JTable Travel_Schedule_ListTable;
    public javax.swing.JLabel customer_name;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
