/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BusBookingSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bassamphone
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bus_id = new javax.swing.JTextField();
        bus_type = new javax.swing.JTextField();
        plate_number = new javax.swing.JTextField();
        total_seats = new javax.swing.JTextField();
        driver_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        StartringPoint = new javax.swing.JComboBox<>();
        Distination = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AddBus = new javax.swing.JButton();
        DepartDate = new com.toedter.calendar.JDateChooser();
        DepartTime = new javax.swing.JTextField();
        TicketPrice = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Bttnlogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(102, 255, 102));

        jPanel5.setBackground(new java.awt.Color(182, 237, 255));

        jPanel2.setBackground(new java.awt.Color(204, 229, 237));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(94, 0, 8));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(94, 0, 8));
        jLabel2.setText("Bus ID :");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(94, 0, 8));
        jLabel3.setText("Bus type :");

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(94, 0, 8));
        jLabel5.setText("plate number :");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(94, 0, 8));
        jLabel6.setText("Total seats :");

        total_seats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_seatsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(94, 0, 8));
        jLabel4.setText("Driver name :");

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(94, 0, 8));
        jLabel7.setText("Destination :");

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(94, 0, 8));
        jLabel8.setText("Starting point :");

        StartringPoint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jerusalem", "Ramallah", "Acre", "Tulkarm", "Nablus", "Haifa", "Hebron", "Gaza", "Jaffa", "Jericho", "Bethlehem", "Nazareth", "Jenin", "Qalqilya", "Tubas" }));
        StartringPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartringPointActionPerformed(evt);
            }
        });

        Distination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jerusalem", "Ramallah", "Acre", "Tulkarm", "Nablus", "Haifa", "Hebron", "Gaza", "Jaffa", "Jericho", "Bethlehem", "Nazareth", "Jenin", "Qalqilya", "Tubas" }));
        Distination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistinationActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(94, 0, 8));
        jLabel9.setText("Depart date :");

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(94, 0, 8));
        jLabel10.setText("Depart time :");

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(94, 0, 8));
        jLabel11.setText("Ticket price :");

        AddBus.setBackground(new java.awt.Color(184, 255, 225));
        AddBus.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        AddBus.setForeground(new java.awt.Color(94, 0, 8));
        AddBus.setText("Add Bus");
        AddBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AddBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                        .addComponent(bus_type, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(50, 50, 50)
                                        .addComponent(bus_id))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(driver_name)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(plate_number, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(total_seats, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StartringPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Distination, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DepartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DepartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bus_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartringPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(driver_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(Distination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bus_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(DepartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(DepartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(plate_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TicketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel6)
                    .addComponent(total_seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(AddBus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel1.setBackground(new java.awt.Color(182, 237, 255));

        Bttnlogout.setBackground(new java.awt.Color(219, 209, 218));
        Bttnlogout.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        Bttnlogout.setForeground(new java.awt.Color(94, 0, 8));
        Bttnlogout.setText("Logout");
        Bttnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnlogoutActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(219, 209, 218));
        jButton1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(94, 0, 8));
        jButton1.setText("Display All Tables");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(94, 0, 8));
        jLabel1.setText("Welcome Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bttnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bttnlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(468, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                AdminFram AdminTablesPage = new AdminFram();
                AdminTablesPage.setVisible(true); // show tables pages
                this.setVisible(false); // hide this page
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/busbookingsystem","root","");
                    // Bus Table
                    String sql1 = "SELECT * FROM `bus-table`";
                    PreparedStatement table1=con.prepareStatement(sql1);
                    ResultSet resultTable1 = table1.executeQuery();
                    while(resultTable1.next()){
                        String bus_id = String.valueOf(resultTable1.getInt("bus-id"));
                        String plate_number = resultTable1.getString("plate-no");
                        String type = resultTable1.getString("bus-type");
                        String total_seats = String.valueOf(resultTable1.getInt("total-seats"));
                        String driver_name = resultTable1.getString("driver-name");
                        
                        String busData[] = {bus_id,plate_number,type,total_seats,driver_name};
                        DefaultTableModel TableModel = (DefaultTableModel)AdminTablesPage.BusTable.getModel();
                        TableModel.addRow(busData);
                    }
                    
                    // Customer Table
                    String sql2 = "SELECT * FROM `customer-table`";
                    PreparedStatement table2 =con.prepareStatement(sql2);
                    ResultSet resultTable2 = table2.executeQuery();
                    while(resultTable2.next()){
                        String customer_id = String.valueOf(resultTable2.getInt("customer-id"));
                        String customer_name = resultTable2.getString("customer-name");
                        String password = resultTable2.getString("password");
                        String username = resultTable2.getString("username");
                        String phone_number = String.valueOf(resultTable2.getInt("phone-number"));
                        String Birth_date = String.valueOf(resultTable2.getDate("birth-date"));
                        
                        String customerData[] = {customer_id,customer_name,phone_number,Birth_date,username,password};
                        DefaultTableModel TableModel = (DefaultTableModel)AdminTablesPage.CustomerTable.getModel();
                        TableModel.addRow(customerData);
                    }
                 
                    
                    // Booking Table
                    String sql4 = "SELECT * FROM `booking-table`";
                    PreparedStatement table4 = con.prepareStatement(sql4);
                    ResultSet resultTable4 = table4.executeQuery();
                    while(resultTable4.next()){
                        String booking_id = String.valueOf(resultTable4.getInt("booking-id"));
                        String bus_id = String.valueOf(resultTable4.getInt("bus-id"));
                        String customer_id = String.valueOf(resultTable4.getInt("customer-id"));
                        String customer_name = resultTable4.getString("customer-name");
                        String paid = resultTable4.getString("paid");
                        String seat_number = String.valueOf(resultTable4.getInt("seat-number"));
                        String BookingData[] = {booking_id,bus_id,customer_id,customer_name,seat_number,paid};
                        DefaultTableModel TableModel = (DefaultTableModel)AdminTablesPage.BookingTable.getModel();
                        TableModel.addRow(BookingData);
                    }
                    
                    // Travel Schedule Table
                    String sql5 = "SELECT * FROM `travel-schedule-table`";
                    PreparedStatement table5 = con.prepareStatement(sql5);
                    ResultSet resultTable5 = table5.executeQuery();
                    while(resultTable5.next()){
                        String travel_id = String.valueOf(resultTable5.getInt("travel-id"));
                        String bus_id = String.valueOf(resultTable5.getInt("bus-id"));
                        String starting_point = resultTable5.getString("starting-point");
                        String destination = resultTable5.getString("destination");
                        String depart_time = resultTable5.getString("depart-time");
                        String depart_date = String.valueOf(resultTable5.getDate("depart-date"));
                        String remaining_seats = String.valueOf(resultTable5.getInt("remaining-seats"));
                        String ticket_price =  String.valueOf(resultTable5.getInt("ticket-price"));
                        String Travel_Schedule[] = {travel_id,bus_id,starting_point,destination,depart_time,depart_date,remaining_seats,ticket_price};
                        DefaultTableModel TableModel = (DefaultTableModel)AdminTablesPage.Travel_ScheduleTable.getModel();
                        TableModel.addRow(Travel_Schedule);
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }    
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBusActionPerformed
        if(bus_id.getText().trim().isEmpty() ||
            bus_type.getText().trim().isEmpty() ||
            plate_number.getText().trim().isEmpty() ||
            total_seats.getText().trim().isEmpty() ||
            driver_name.getText().trim().isEmpty()
        ){
           JOptionPane.showMessageDialog(null, "Can't Add bus with null values");
        }else{
            try{
                int busID = Integer.parseInt(bus_id.getText());
                int totalSeats = Integer.parseInt(total_seats.getText());
                int remaining_seats = Integer.parseInt(total_seats.getText());
                int ticket_price = Integer.parseInt(TicketPrice.getText());
                String Starting = StartringPoint.getSelectedItem().toString();
                String destination = Distination.getSelectedItem().toString();
                try{
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/busbookingsystem", "root", "");
                    // Add to Bus table
                    String sql = "INSERT INTO `bus-table` (`bus-id`, `bus-type`, `driver-name`, `plate-no`, `total-seats`) VALUES (?,?,?,?,?)";
                    PreparedStatement stmt = con.prepareStatement(sql);
                    stmt.setInt(1,busID);
                    stmt.setString(2,bus_type.getText().trim());
                    stmt.setString(3, driver_name.getText().trim());
                    stmt.setString(4, plate_number.getText().trim());
                    stmt.setInt(5, totalSeats);
                    stmt.executeUpdate();
                    
                    // Add to travel schedule table

                    String sql2 = "INSERT INTO `travel-schedule-table` (`travel-id`,`bus-id`, `depart-date`, `depart-time`, `destination`, `remaining-seats`,`starting-point`,`ticket-price`) VALUES (null,?,?,?,?,?,?,?)";
                    PreparedStatement stmt2 = con.prepareStatement(sql2);
                    stmt2.setInt(1,busID);
                    java.sql.Date sqlDate = new java.sql.Date((DepartDate.getDate()).getTime()); // convert from java date to sql date
                    stmt2.setDate(2, sqlDate);
                    stmt2.setString(3, DepartTime.getText().trim());
                    stmt2.setString(4,destination);
                    stmt2.setInt(5,remaining_seats);
                    stmt2.setString(6,Starting);
                    stmt2.setInt(7,ticket_price);
                    stmt2.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Bus added successfully");
                    con.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, e);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Add integer values to Bus-id/Total-seats");
            }
        }

            
           
    }//GEN-LAST:event_AddBusActionPerformed

    private void DistinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DistinationActionPerformed

    private void BttnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnlogoutActionPerformed
        UserLogin user_login = new UserLogin();
        user_login.setVisible(true); // go to login page
        this.setVisible(false); // hide this page
    }//GEN-LAST:event_BttnlogoutActionPerformed

    private void total_seatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_seatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_seatsActionPerformed

    private void StartringPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartringPointActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartringPointActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBus;
    private javax.swing.JButton Bttnlogout;
    private com.toedter.calendar.JDateChooser DepartDate;
    private javax.swing.JTextField DepartTime;
    private javax.swing.JComboBox<String> Distination;
    private javax.swing.JComboBox<String> StartringPoint;
    private javax.swing.JTextField TicketPrice;
    private javax.swing.JTextField bus_id;
    private javax.swing.JTextField bus_type;
    private javax.swing.JTextField driver_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField plate_number;
    private javax.swing.JTextField total_seats;
    // End of variables declaration//GEN-END:variables
}
