/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BusBookingSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author bassamphone
 */
public class ConfirmBooking extends javax.swing.JFrame {

    /**
     * Creates new form BookingForm
     */
    public ConfirmBooking() {
        initComponents();

    }
            
    ConfirmBooking(String UserName,int UserID){
        //customer_id.setText(Integer.toString(UserID));
        customer_name.setText(UserName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bus_id = new javax.swing.JLabel();
        starting_point = new javax.swing.JLabel();
        destination = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        remaining_seats = new javax.swing.JLabel();
        depart_date = new javax.swing.JLabel();
        depart_time = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BttnBook = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        number_of_seat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Paid = new javax.swing.JComboBox<>();
        customer_id = new javax.swing.JLabel();
        customer_name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ticket_price = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 184, 190));

        lblRegister.setFont(new java.awt.Font("Palatino Linotype", 1, 28)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(94, 0, 8));
        lblRegister.setText("Bus Ticket Booking System");

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(94, 0, 8));
        jLabel1.setText("Confirm Booking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegister))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 225, 184));

        jPanel3.setBackground(new java.awt.Color(255, 225, 184));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(94, 0, 8));
        jLabel2.setText("Bus ID :");

        bus_id.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        bus_id.setForeground(new java.awt.Color(94, 0, 8));
        bus_id.setText("jLabel9");

        starting_point.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        starting_point.setForeground(new java.awt.Color(94, 0, 8));
        starting_point.setText("jLabel9");

        destination.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        destination.setForeground(new java.awt.Color(94, 0, 8));
        destination.setText("jLabel9");

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(94, 0, 8));
        jLabel5.setText("Destination :");

        jLabel4.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(94, 0, 8));
        jLabel4.setText("Depart time :");

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(94, 0, 8));
        jLabel8.setText("Depart date :");

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(94, 0, 8));
        jLabel7.setText("Remaining seats :");

        remaining_seats.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        remaining_seats.setForeground(new java.awt.Color(94, 0, 8));
        remaining_seats.setText("jLabel9");

        depart_date.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        depart_date.setForeground(new java.awt.Color(94, 0, 8));
        depart_date.setText("jLabel9");

        depart_time.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        depart_time.setForeground(new java.awt.Color(94, 0, 8));
        depart_time.setText("jLabel9");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(94, 0, 8));
        jLabel3.setText("Starting point :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(starting_point)
                    .addComponent(remaining_seats)
                    .addComponent(depart_date)
                    .addComponent(destination)
                    .addComponent(depart_time)
                    .addComponent(bus_id))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bus_id))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(starting_point)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(destination))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(depart_time))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(depart_date))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(remaining_seats))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 225, 184));

        BttnBook.setBackground(new java.awt.Color(255, 184, 190));
        BttnBook.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        BttnBook.setForeground(new java.awt.Color(94, 0, 8));
        BttnBook.setText("Book!");
        BttnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttnBookActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(94, 0, 8));
        jLabel12.setText("Customer ID :");

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(94, 0, 8));
        jLabel10.setText("Customer name :");

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(94, 0, 8));
        jLabel9.setText("Number of seat :");

        number_of_seat.setForeground(new java.awt.Color(94, 0, 8));

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(94, 0, 8));
        jLabel11.setText("Pay now ?");

        Paid.setForeground(new java.awt.Color(94, 0, 8));
        Paid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        Paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaidActionPerformed(evt);
            }
        });

        customer_id.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        customer_id.setForeground(new java.awt.Color(94, 0, 8));
        customer_id.setText("jLabel11");

        customer_name.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        customer_name.setForeground(new java.awt.Color(94, 0, 8));
        customer_name.setText("jLabel11");

        jButton1.setBackground(new java.awt.Color(255, 184, 190));
        jButton1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(94, 0, 8));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(94, 0, 8));
        jLabel6.setText("Ticket price :");

        ticket_price.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        ticket_price.setForeground(new java.awt.Color(94, 0, 8));
        ticket_price.setText("jLabel9");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customer_name)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6))
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addComponent(BttnBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(number_of_seat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customer_id)
                                    .addComponent(ticket_price, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(customer_id))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(customer_name))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(number_of_seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ticket_price))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Paid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BttnBook)
                    .addComponent(jButton1))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(469, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaidActionPerformed

    private void BttnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttnBookActionPerformed
        int BusID = Integer.parseInt(bus_id.getText());
        try{
            int seat_number = Integer.parseInt(number_of_seat.getText());
            String paid = Paid.getSelectedItem().toString();
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/busbookingsystem","root","");
                String sql = "SELECT `customer-id`, `customer-name` FROM `customer-table` WHERE `customer-name` =?";
                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setString(1, customer_name.getText());
                ResultSet result1 = stmt.executeQuery();
                
                String sql2="SELECT `bus-id`FROM `bus-table` WHERE `bus-id`=?";
                PreparedStatement stmt2 = con.prepareStatement(sql2);
                stmt2.setInt(1, BusID);
                ResultSet result2 = stmt2.executeQuery();
                if(result1.next() && result2.next()){
                    int CustomerID = result1.getInt("customer-id");
                    String CustomerName = result1.getString("customer-name");
                    int Bus_ID = result2.getInt("bus-id");
                    
                    String sql3 = "INSERT INTO `booking-table` (`booking-id`,`customer-id`,`bus-id`,`customer-name`,`seat-number`,`paid`) VALUES (null,?,?,?,?,?)";
                    PreparedStatement stmt3 = con.prepareStatement(sql3);
                    stmt3.setInt(1, CustomerID);
                    stmt3.setInt(2, Bus_ID);
                    stmt3.setString(3, CustomerName);
                    stmt3.setInt(4, seat_number);
                    stmt3.setString(5, paid);
                    stmt3.executeUpdate();
                    int remaining = Integer.parseInt(remaining_seats.getText());
                    int number_of_seats = remaining - 1 ;
                    String upadte_seats = "UPDATE `travel-schedule-table` SET `remaining-seats`=? WHERE `bus-id`=?";
                    PreparedStatement update = con.prepareStatement(upadte_seats);
                    update.setInt(1,number_of_seats);
                    update.setInt(2,Bus_ID);
                    update.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Ticket booked successfully");
                    AddBooking Booking_page = new AddBooking();
                    Booking_page.customer_name.setText(customer_name.getText());
                    this.setVisible(false); // hide this page
                    Booking_page.setVisible(true); // return to booking page
                    
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                System.out.println(e);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Add integer value for number of seat!!");
        }
    }//GEN-LAST:event_BttnBookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddBooking user = new AddBooking();
        user.setVisible(true); // return to booking page
        this.setVisible(false); // hide this page
        user.customer_name.setText(customer_name.getText());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttnBook;
    private javax.swing.JComboBox<String> Paid;
    public javax.swing.JLabel bus_id;
    public javax.swing.JLabel customer_id;
    public javax.swing.JLabel customer_name;
    public javax.swing.JLabel depart_date;
    public javax.swing.JLabel depart_time;
    public javax.swing.JLabel destination;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JTextField number_of_seat;
    public javax.swing.JLabel remaining_seats;
    public javax.swing.JLabel starting_point;
    public javax.swing.JLabel ticket_price;
    // End of variables declaration//GEN-END:variables
}
