/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busbookingsystem;

/**
 *
 * @author user
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblId = new javax.swing.JLabel();
        LblName = new javax.swing.JLabel();
        LblUsername = new javax.swing.JLabel();
        LblPhone = new javax.swing.JLabel();
        LblBirthDate = new javax.swing.JLabel();
        IpPhone = new javax.swing.JTextField();
        IpBirthDate = new javax.swing.JTextField();
        IpName = new javax.swing.JTextField();
        IpID = new javax.swing.JTextField();
        LblPassword = new javax.swing.JLabel();
        IpUsername = new javax.swing.JTextField();
        IpPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LblId.setText("ID");
        getContentPane().add(LblId);
        LblId.setBounds(63, 42, 31, 13);

        LblName.setText("Name");
        getContentPane().add(LblName);
        LblName.setBounds(63, 81, 31, 13);

        LblUsername.setText("Username");
        getContentPane().add(LblUsername);
        LblUsername.setBounds(63, 181, 76, 22);

        LblPhone.setText("Phone number");
        LblPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(LblPhone);
        LblPhone.setBounds(63, 117, 70, 13);

        LblBirthDate.setText("Birth Date");
        getContentPane().add(LblBirthDate);
        LblBirthDate.setBounds(63, 150, 60, 13);
        getContentPane().add(IpPhone);
        IpPhone.setBounds(210, 120, 55, 19);
        getContentPane().add(IpBirthDate);
        IpBirthDate.setBounds(210, 150, 55, 19);

        IpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpNameActionPerformed(evt);
            }
        });
        getContentPane().add(IpName);
        IpName.setBounds(210, 80, 55, 19);

        IpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpIDActionPerformed(evt);
            }
        });
        getContentPane().add(IpID);
        IpID.setBounds(210, 40, 55, 19);

        LblPassword.setText("Password");
        getContentPane().add(LblPassword);
        LblPassword.setBounds(60, 220, 61, 24);

        IpUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(IpUsername);
        IpUsername.setBounds(200, 190, 83, 19);
        getContentPane().add(IpPassword);
        IpPassword.setBounds(200, 230, 83, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IpIDActionPerformed

    private void IpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IpNameActionPerformed

    private void IpUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IpUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IpBirthDate;
    private javax.swing.JTextField IpID;
    private javax.swing.JTextField IpName;
    private javax.swing.JPasswordField IpPassword;
    private javax.swing.JTextField IpPhone;
    private javax.swing.JTextField IpUsername;
    private javax.swing.JLabel LblBirthDate;
    private javax.swing.JLabel LblId;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblPassword;
    private javax.swing.JLabel LblPhone;
    private javax.swing.JLabel LblUsername;
    // End of variables declaration//GEN-END:variables
}
